---
name: "build"

on:  # yamllint disable-line rule:truthy
  pull_request:
  push:
    branches: master

jobs:
  build:
    name: Go ${{ matrix.go-version }} | Ubuntu
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go-version: ['1.16', '1.17', '1.18', '1.19']

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
          check-latest: true
          cache: true

      - name: Run tests
        run: |
          make test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
